services:
    orynider.translatetitle.listener:
        class: orynider\translatetitle\event\listener
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
